#!/bin/sh

# This transcript is taken from Osamu Dazai "New Hamlet"
# http://www.aozora.gr.jp/cards/000035/files/1576_8585.html

SSLACK=http://localhost:8080

curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=皆も疲れたろうね。御苦労でした。先王が、まことに突然、亡（な）くなって、その涙も乾かぬうちに、わしのような者が位を継ぎ、また此（こ）の度はガーツルードと新婚の式を行い、わしとしても具合の悪い事でしたが、すべて此のデンマークの為（ため）です。皆とも充分に相談の上で、いろいろ取りきめた事ですから、地下の兄、先王も、皆の私心無き憂国の情にめんじて、わしたちを許してくれるだろうと思う。まことに此の頃（ごろ）のデンマークは、ノーウエーとも不仲であり、いつ戦争が起るかも知れず、王位は、一日も空けて置く事が出来なかったのです。王子ハムレットは若冠ゆえ、皆のすすめに依（よ）って、わしが王位にのぼったのですが、わしとても先王ほどの手腕は無し、徳望も無ければ、また、ごらんのとおり風采（ふうさい）もあがらず、血をわけた実の兄弟とも思われぬくらいに不敏の弟なのですから、果して此の重責に堪え得るかどうか、外国の侮（あなど）りを受けずにすむかどうか頗（すこぶ）る不安に思って居（お）りましたところ、かねて令徳の誉（ほまれ）高いガーツルードどのが、一生わしの傍にいて、国の為、わしの力になってくれる事になりましたので、もはや王城の基礎も確固たり、デンマークも安泰と思います。皆も御苦労でした。先王が亡くなられてから今日まで、もう二箇月にもなりますが、わしには何もかも夢のようです。でも皆の聡明（そうめい）な助言に依って、どうやら大過なく、ここまでは、やって来ました。いかにも未熟の者ですから、皆も、今日以後、変らず忠勤の程を見せ、わしを安心させて下さい。ああ、忘れていた。レヤチーズが、わしに何か願いがあるとか言っていましたね。なんですか？"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=laertes" -d "text=はい。実は、フランスへ、もう一度遊学に行かせていただきたいと思っているのでございますが。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=その事でしたら、かまいません。君にも此の二箇月間、ずいぶん働いてもらいました。もう、こちらは、どうやら一段落ですから、ゆっくり勉強しておいでなさい。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=laertes" -d "text=恐れいります。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=君の父にも相談した上の事でしょうね。ポローニヤス、どうですか？"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=polonius" -d "text=はい。どうにも、うるさく頼みますので、とうとう昨夜、私も根負け致（いた）しまして、それでは王さまにお願いして見よと申し聞かせた次第でございます。ヘッヘ、どうも若いものには、フランスの味が忘れかねるようでございます。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=無理もない。レヤチーズ、子供にとっては、王の裁可よりも、父の許しのほうが大事です。一家の和合は、そのまま王への忠義です。父の許しがあったならば、それでよい。からだを損わぬ程度に、遊んでおいで。若い時には、遊ぶのにも張り合いがあるから、うらやましい。ハムレットは、このごろ元気が無いようですが、君もフランスへ行きたいのですか？"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=hamlet" -d "text=僕ですか？　からかわないで下さい。僕は地獄へ行くんです。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=何を、ぷんぷんしているのです。あ、そうか。君は、ウイッタンバーグの大学へ、また行きたいと言っていましたね。でも、それは怺（こら）えて下さい。わしからお願いします。君は、もうすぐ此のデンマークの王位を継がなければならぬ人です。今は国も、めんどうな時ですから、わしが仮に王位に即（つ）きましたが、此の危機が去って、人々の心も落ちつけば、わしは君に跡を継いでもらって、ゆっくり休息したいと思って居ります。それゆえ君は、いまからわしの傍にいて、少しずつ政治を見習うように心掛けなければいけません。いや、わしを助けてもらいたいのです。どうか、大学へ行くのは、あきらめて下さい。これは、父としての願いでもあるのです。君が、いなくなると、王妃だって淋（さび）しがるでしょう。君は、このごろ健康を害しているようにも見えます。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=hamlet" -d "text=レヤチーズ、――"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=laertes" -d "text=はい。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=hamlet" -d "text=君は、いい父を持って仕合せだね。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=queen" -d "text=ハムレット、なんという事を、おっしゃるのです。私には、あなたが、ふてくされているようにしか思われません。そんな厭味（いやみ）な、気障（きざ）な態度は、およしなさい。不満があるなら男らしく、はっきりおっしゃって下さい。私は、そんな言いかたは、きらいです。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=hamlet" -d "text=はっきり言いましょうか。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=わかっています。わしは此の機会に、君と二人きりでゆっくり話してみたい。王妃も、そんなに怒るものではありません。若い者には、若い者の正当な言いぶんがある筈（はず）です。わしにも、反省しなければならぬ事が、まだまだ、あるように思われます。ハムレット、泣かずともよい。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=queen" -d "text=なに、そら涙ですよ。この子は、小さい時から、つくり泣きが上手だったのです。あまり、いたわらずに、うんとお叱（しか）りになって下さい。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=ガーツルード、言葉をつつしみなさい。ハムレットは、あなたひとりの子ではありません。ハムレットは、デンマーク国の王子です。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=queen" -d "text=それだから私も言うのです。ハムレットだって、もう二十三になります。いつまで、甘えているのでしょう。私は生みの母として此の子を恥ずかしく思います。ごらん下さい。きょうは王の初謁見式（えっけんしき）だというのに、この子ばかりは、わざと不吉な喪服なんかを着て、自分では悲壮のつもりで居るのでしょうが、それがどんなに私たちを苦しめる事なのか、この子は思ってもみないのです。私には、この子の考えている事くらい、なんでもわかります。この喪服だって、私たちへのいやがらせです。先王の死を、もはや忘れたのかという、当てつけのつもりなのでしょう。誰も忘れてやしません。心の中では誰だって、深く悲しんでいるのですが、いまは、その悲しみに沈んでばかりも居られません。私たちは、デンマークの国を思わなければいけません。デンマークの民を思わなければいけません。私たちには、悲しむ事さえ自由ではないのです。自分の身であって、自分のものではないのです。ハムレットには、それが、ちっともわかっていないのです。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=king" -d "text=や、それは酷だ。そんな、追いつめるような言いかたをしては、いけません。人を無益に傷つけるだけの事です。王妃には、生みの母という安心があって、その愛情を頼みすぎて、そんな事を言うのでしょうが、若い者にとっては、陰の愛情よりも、あらわれた言葉のほうが重大なのです。わしにも、覚えがあります。言葉に拠（よ）って、自分の全部が決定されるような気がするものです。王妃も、きょうは、どうかしていますよ。ハムレットが喪服を着ていたって、少しも差しつかえ無いと思います。少年の感傷は純粋なものです。それを、わしたちの生活に無理に同化させようとするのは、罪悪です。大事にしてやらなければいけません。わしたちこそ、この少年の純粋を学ばなければいけないのかも知れません。わかるとは思っていながら、いつのまにやら、わしたちは大事なものを失っている場合もあるのです。とにかく、わしはハムレットと二人きりで、ゆっくり話してみたいと思いますから、みんなは暫（しばら）く向うへ行っていて下さい。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=queen" -d "text=そんなら、お願い致します。私も少し言いすぎたようですが、でも、あなたも義理ある仲だと思って、此の子に優しくしすぎるようです。それでは、いつまで経（た）っても、この子は立派になりません。先王がおいでになったとしても、きょうの此の子の態度には、きっとお怒りになり、此の子をお打ちになったでしょう。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=hamlet" -d "text=打ったらいいんだ。"
curl $SSLACK/slack-webhook -d token=SLACK_TOKEN_HERE  -d "channel_name=new_hamlet"  -d "timestamp=1355517523.000005" -d "user_name=queen" -d "text=また、何をおっしゃる。もっと素直におなりなさい。"
